name: Deploy FE

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i #yarn
      - name: Build
        run: npm run build #yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
